name: QA

on: pull_request

concurrency:
  group: qa-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Clone repository
      uses: actions/checkout@v5
    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22.x'
    - name: Install dependencies
      run: |
        npm ci
    - name: Run QA
      run: |
        npm run qa
    - name: Run build
      run: |
        npm run build
