name: QA

on: pull_request

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [ '22.x' ]
        os: [ ubuntu-latest, macos-latest ]

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci
    - name: Run QA
      run: |
        npm run qa
    - name: Run build
      run: |
        npm run build
